services:
    - type: web
      name: asl-backend
      env: python
      plan: free
      buildCommand: pip install -r requirements.txt
      startCommand: python app.py
      envVars:
          - key: PYTHON_VERSION
            value: 3.10.11
          - key: PORT
            value: 10000
          - key: ENV
            value: production
      healthCheckPath: /healthz
      autoDeploy: true
